Add create project and build config tests
Gimadeev/teamcity-tests pull request #1
Opened 2023-12-05 11:25 UTC by Gimadeev

2023-12-14 13:56 UTC, AlexPshe requested changes
Привет!

Большое спасибо за качественное выполнение задания!

Я добавила несколько комментов по улучшению - нужно пофиксить их за неделю и будет зачтено ⚡️

2023-12-14 13:56 UTC, AlexPshe commented on src/test/java/com/example/teamcity/api/BuildConfigurationTest.java
> +        softy.assertThat(buildConfiguration.getId()).isEqualTo(testData.getBuildType().getId());
А давай попробуем сравнить через сущности, а не по полям? Думаю, будет более масштабируемо)

2023-12-14 13:56 UTC, AlexPshe commented on src/test/java/com/example/teamcity/api/BuildConfigurationTest.java
> +                .body(Matchers.containsString("When creating a build type, non empty name should be provided"));
Ошибки можно вынести в отдельный Errors статический класс и сделать константами 🙌

2023-12-14 13:56 UTC, AlexPshe commented on src/test/java/com/example/teamcity/api/BuildConfigurationTest.java
> +                .body(Matchers.containsString("Build configuration with name \"" + secondTestData
Можно использовать format для более красивой параметризации строки, пример:
https://stackoverflow.com/questions/17364632/java-generating-strings-with-placeholders

2023-12-15 18:51 UTC, Gimadeev commented on src/test/java/com/example/teamcity/api/BuildConfigurationTest.java
> +                .body(Matchers.containsString("When creating a build type, non empty name should be provided"));
done

2023-12-15 19:24 UTC, Gimadeev commented on src/test/java/com/example/teamcity/api/BuildConfigurationTest.java
> +                .body(Matchers.containsString("Build configuration with name \"" + secondTestData
done

2023-12-17 14:24 UTC, AlexPshe approved these changes
Отлично, все зачтено!

2023-12-17 20:32 UTC, merged