Added UI tests: CreateNewProjectTest, CreateNewBuildTest
Gimadeev/teamcity-tests pull request #2
Opened 2023-12-21 20:42 UTC by Gimadeev

2023-12-29 13:02 UTC, AlexPshe requested changes
Привет! 

Спасибо за выполненное ДЗ, все гуд, но нужно ответить на коммент до 10 января и зачтем за сданное 🔥

С наступающим! 🎄

2023-12-29 13:02 UTC, AlexPshe commented on src/test/java/com/example/teamcity/ui/CreateNewProjectTest.java
> +        var project = new CheckedProject(Specifications.getSpec().superUserSpec())
Хмм, а точно ли тут сработает поиск по project id, мы же сгенерировали его в testData, а создаем project через UI потом?

2024-01-07 11:29 UTC, Gimadeev commented on src/test/java/com/example/teamcity/ui/CreateNewProjectTest.java
> +        var project = new CheckedProject(Specifications.getSpec().superUserSpec())
Привет! да, все корректно отрабатывает. При создании проекта мануально мы берем name, description и id из testData. и в итоге у нас данные в testData и в созданном проекте идентичны.
Можно было бы не сеттить id, он сам из имени может создать его если не трогать, но я решил в рамках теста проверить что все данные, которые введет пользователь сохранятся корректно. 
В методе 'createProjectManually' все это происходит. 
Но если есть какие консерны, могу поправить)

2024-01-21 13:57 UTC, AlexPshe approved these changes
Теперь ДЗ засчитано, спасибо! 🔥

2024-01-21 13:57 UTC, AlexPshe commented on src/test/java/com/example/teamcity/ui/CreateNewProjectTest.java
> +        var project = new CheckedProject(Specifications.getSpec().superUserSpec())
Отлично, тогда огонь!

2024-01-22 19:12 UTC, merged